const CardDetails = [
    {
        projectName: "Augmented Reality Viewer",
        description: "An AR viewer that displays artificial objects overlaid on images of a real 3D scene using point cloud generated by COLMAP.",
        gitLink: "https://github.com/ShaunFrost/ar_viewer",
        linkName: "Check Repo"
    },
    {
        projectName: "Urban Scenes Classifier",
        description: "Classification of Google Urban Scenes dataset images into the corresponding city.",
        gitLink: "https://github.com/ShaunFrost/urban_scenes_classifier",
        linkName: "Check Repo"
    },
    {
        projectName: "Loop Info Pass",
        description: "Creating a compiler pass that prints loop related info using LLVM.",
        gitLink: "https://github.com/ShaunFrost/loop-info-llvm",
        linkName: "Check Repo"
    },
    {
        projectName: "Anime Hangman",
        description: "Anime character version of Hangman built using react.",
        gitLink: "https://shaunfrost.github.io/hangman/",
        linkName: "Try the Game"
    }
];
export default CardDetails;